name: Test Workflow

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    uses: tehw0lf/workflows/.github/workflows/build-test-publish.yml@main
    with:
      event_name: ${{ github.event_name }}
      tool: npm
      artifact_path: dist
      publish_npm: "false"
      publish_docker: "false"
      publish_python: "false"
      publish_firefox_extension: "false"
      publish_android: "false"
      publish_github_release: "false"
